import { coresBase } from "./stylesGeral";
import { StyleSheet } from "react-native";

export const styleTelaResultado = StyleSheet.create({
  resultadoTotal: {
    fontSize: 30,
    fontFamily: "Jost-Bold",
    fontWeight: 900,
    color: coresBase.verdeMedio,
    marginTop: 10,
    marginBottom: 20,
    alignSelf: "center",
  },
  containerInfo: {
    width: "90%",
    flexDirection: "row",
    marginHorizontal: 20,
    justifyContent: "space-between",
    marginBottom: 110,
  },
  resultadoMeta: {
    fontSize: 14,
    color: coresBase.verdeEscuro,
  },
  secaoTitulo: {
    fontSize: 25,
    fontFamily: "Jost-Bold",
    fontWeight: 900,
    color: coresBase.verdeMedio,
    marginTop: 20,
    marginBottom: 20,
    marginHorizontal: 5,
  },
  graficoContainer: {
    width: "90%",
    height: 250,
    borderRadius: 16,
    backgroundColor: "#fff",
    paddingVertical: 16,
    paddingHorizontal: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderWidth: 1,
    borderColor: coresBase.verdeMedio,
    alignSelf: "center",
  },
  barraColuna: {
    width: 58,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  barra: {
    width: 26,
    borderRadius: 10,
  },
  barraValor: {
    fontSize: 12,
    color: "#333",
    marginBottom: 6,
  },
  barraLabel: {
    marginTop: 8,
    fontSize: 12,
    color: "#333",
    fontWeight: 600,
  },
  totalComparacao: {
    marginTop: 5,
    marginBottom: 24,
    padding: 12,
    marginHorizontal: 13,
  },
  totalComparacaoLabel: {
    fontSize: 17,
    color: coresBase.verdeMedio,
    fontWeight: 700,
  },
  feedbackContainer: {
    borderRadius: 12,
    width: "100%",
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: coresBase.verdeClaro,
    marginVertical: 20,
    paddingVertical: 25,
    paddingHorizontal: 15,
  },
  feedbackTexto: {
    fontSize: 18,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 26,
    color: coresBase.verdeEscuro,
  },
  feedbackTextoTitulo: {
    fontSize: 32,
    color: "#ff3e3e",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 25,
  },
  feedbackEmoji: {
    fontSize: 20,
    marginTop: 10,
    alignSelf: "center",
  },
});
